name: alboe

###
# The ALBOE operations services definition.
###

services:

###
# Infrastructure
# IP Range - 172.18.1.0/24
###

  proxy:
    container_name: proxy
    image: traefik
    command: --configFile=/config/config.yaml
    restart: unless-stopped
    environment:
      - CF_DNS_API_TOKEN=${PROXY_TOKEN_CF_API}
    networks:
      systems:
        ipv4_address: 172.18.1.10
    ports:
      - "53:53/tcp" # dns/tcp
      - "53:53/udp" # dns/udp
      - "80:80/tcp" # http
      - "443:443/tcp" # https
      - "50000:50000/udp" # vpn
    volumes:
      - type: bind
        source: ${STORAGE}/proxy/config.yaml
        target: /config/config.yaml
      - type: bind
        source: ${STORAGE}/proxy/logs
        target: /logs
      - type: bind
        source: ${STORAGE}/proxy/certs
        target: /certs

  dns:
    container_name: dns
    image: ubuntu/bind9
    restart: unless-stopped
    environment:
      - BIND9_USER=root
      - TZ=UTC
    networks:
      systems:
        ipv4_address: 172.18.1.11
    volumes:
      - type: bind
        source: ${STORAGE}/dns/zones
        target: /etc/bind/zones
      - type: bind
        source: ${STORAGE}/dns/named.conf
        target: /etc/bind/named.conf
      - type: bind
        source: ${STORAGE}/dns/cache
        target: /var/cache/bind
      - type: bind
        source: ${STORAGE}/dns/records
        target: /var/lib/bind

  ddns:
    container_name: ddns
    image: favonia/cloudflare-ddns
    restart: unless-stopped
    networks:
      systems:
        ipv4_address: 172.18.1.12
    read_only: true
    cap_drop: [all]
    security_opt: [no-new-privileges:true]
    environment:
      - CLOUDFLARE_API_TOKEN=${DDNS_TOKEN_CF_API}
      - DOMAINS=${DDNS_DOMAINS}
      - IP6_PROVIDER=none
      - PROXIED=true

  vpn:
    container_name: vpn
    image: linuxserver/wireguard
    restart: unless-stopped
    networks:
      systems:
        ipv4_address: 172.18.1.13
    cap_add:
      - NET_ADMIN
      - SYS_MODULE
    environment:
      - PEERS=${VPN_PEERS}
      - PEERDNS=172.16.1.10
      - PGID=${PGID}
      - PUID=${PUID}
      - SERVERURL=${VPN_HOST}
      - SERVERPORT=50000
      - TZ=${COMMON_TZ}
      - INTERNAL_SUBNET=${VPN_SUBNET}
      - ALLOWEDIPS=0.0.0.0/0
    volumes:
      - type: bind
        source: ${STORAGE}/vpn/config
        target: /config
      - type: bind
        source: ${STORAGE}/vpn/modules
        target: /lib/modules
    sysctls:
      - net.ipv4.conf.all.src_valid_mark=1

###
# Applications
# IP Range - 172.18.2.0/24
###

  share:
    image: stonith404/pingvin-share
    container_name: share
    restart: unless-stopped
    environment:
      - TRUST_PROXY=true
    volumes:
      - type: bind
        source: ${STORAGE}/share/data
        target: /opt/app/backend/data
      - type: bind
        source: ${STORAGE}/share/images
        target: /opt/app/frontend/public/img
      - type: bind
        source: ${STORAGE}/share/config.yaml
        target: /opt/app/config.yaml
    networks:
      systems:
        ipv4_address: 172.18.2.10


networks:
  systems:
    name: systems
    external: false
    ipam:
      config:
        - subnet: "172.18.0.0/16"
