version: '3'

services:
  # systems
  proxy:
    container_name: proxy
    image: traefik
    networks:
      games:
        ipv4_address: 192.168.3.10
      systems:
        ipv4_address: 192.168.2.100
    ports:
      - target: 12000 # games/pal-world/game
        published: 12000
        protocol: udp
        mode: host
      - target: 12001 # games/pal-world/rcon
        published: 12001
        protocol: udp
        mode: host
      - target: 12010 # games/minecraft-java/game
        published: 12010
        protocol: tcp
        mode: host
      - target: 12011 # games/minecraft-java/rcon
        published: 12011
        protocol: tcp
        mode: host
    restart: unless-stopped
    volumes:
      - type: bind
        source: ./proxy/storage
        target: /etc/traefik

  # games
  minecraft-java:
    build:
      args:
        - MINECRAFT_VERSION_NUMBER=1.20.4
        - PAPER_BUILD_NUMBER=397
        - EULA=true
      context: ./minecraft-java
      dockerfile: Dockerfile
    container_name: minecraft-java
    environment:
      - MEMORY_MAX=4G
      - MEMORY_MIN=2G
    image: minecraft-java:1.20.4-paper.397
    networks:
      internal:
        ipv4_address: 192.168.3.101
    ports:
      - target: 25565 # minecraft-java
        published: 25565
        protocol: tcp
        mode: host
      - target: 25575 # minecraft-java-rcon
        published: 25575
        protocol: tcp
        mode: host
    restart: unless-stopped
    volumes:
      - type: bind
        source: ./minecraft-java/storage
        target: /minecraft

  pal-world:
    container_name: pal-world
    environment:
      - PORT=8211
      - PLAYERS=30
      - MULTITHREADING=true
      - COMMUNIty=false
    image: thijsvanloef/palworld-server-docker
    networks:
      games:
        ipv4_address: 192.168.3.100
    ports:
      - target: 8211 # game
        published: 8211
        protocol: udp
        mode: host
      - target: 27015 # rcon
        published: 27015
        protocol: udp
        mode: host
    restart: unless-stopped
    volumes:
      - type: bind
        source: ./pal-world/storage
        target: /palworld

networks:
  games:
    ipam:
      config:
        - subnet: "192.168.3.0/24"
    name: games

  systems:
    ipam:
      config:
        - subnet: "192.168.2.0/24"
    name: systems
